---
title: "HW2-KS"
format: html
editor: visual
---

## Homework 2: Quarto and Markdown

The following homework will include basic practice using the markdown language and formatting documents with Quarto.

1.  In the first-level heading (in the title of the document), name your homework - "Homework 2: YOUR NAME'
2.  Name a second-level heading: 'Intro to the Spotify data'
3.  Below the heading, write a sentence describing the Spotify data. State that example data is listed in the table below, and add a cross-reference link to the table. Then write a sentence stating that the data can be imported using the following code:
4.  Write a chunk of code demonstrating one method of reading in the Spotify data (find info [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md))
5.  Write a chunk of R code which outputs the first five rows and five columns of the class dataset as a table (use knitr::kable) and titles the table 'Table 1: Spotify Data Example'. Hide the code chunk but output the table, which should be linked appropriately to #3 ([hint](https://quarto.org/docs/authoring/cross-references.html)).
6.  Turn in both a .qmd and .html file 'HW2-LASTNAME.FIRSTNAME' by uploading to your personal GitHub Repository.
