---
title: "Homework 3"
format: html
editor: visual
---

This week's homework will warm us up to collaboration on GitHub.

1.  Create a branch in your personal GitHub Repository called "HW3"
2.  Add a file in this branch titled 'Homework 3' and add some code that defines three new variables in the Spotify data - suppress this code in the output so that it is not shown
3.  Make a table with your new variable names and other information that you would want about these variables. Add some text that describes the table and add a cross-reference to the table in your text, output the table but suppress the code that you used to make it.
4.  Render to HTML, commit, and push, but make sure that it does not push this to github (use your .gitignore file)
5.  Render to PDF, commit, and push.
6.  Open a 'pull request' to pull this Homework 3 branch back to your main branch. Leave the pull request open for me :)
7.  With your pre-registration partners, make a new public repository for your pre-registration (one person should make it then have others fork the repo).
8.  Make and save a new dataset that adds all of the new variables that group members have created, push this dataset to the repo
9.  send me the repo link via Slack so that I can fork it to the class GitHub
